### ISSUE TITLE
[New Entry Suggestion] Joseph M. Hellerstein, Michael Stonebraker, James Hamilton. Architecture of a Database System. Foundations and Trends in Databases (2007)

### ISSUE THREAD

**Issue by rm206** [lonng/db-papers#3]
Following is the link to the text - https://dsf.berkeley.edu/papers/fntdb07-architecture.pdf

**Comment by lonng** [comment]
@rm206 Thanks for your advice and I have added this paper.

Ref: https://github.com/lonng/db-papers/commit/fc69ac725a110c32de8a222f9815fe7496ba3454
